services:
  - type: web
    name: lesportaal-api
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/El-Rico/glr4-backend
    branch: main
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        generateValue: true

  - type: web
    name: lesportaal-web
    env: node
    plan: free
    # Update the following line with your Remix GitHub repo
    repo: https://github.com/El-Rico/glr4-frontend
    branch: master
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: STRAPI_URL_BASE
        fromService:
          type: web
          name: lesportaal-api
          envVarKey: RENDER_EXTERNAL_URL

databases:
  - name: strapi
    plan: free # This database will expire 90 days after creation
